scheduled_tweets/config/routes.rb
Rails.application.routes.draw do
 #GET /about
  get "about", to: "about#index"

  get "sign_up", to: "registration#new"

  post "sign_up", to: "registration#create"

  get "sign_in", to: "sessions#new"

  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  # get "/", to: "main#index" #Method one
  root to: "main#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

scheduled_tweets/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

scheduled_tweets/app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

scheduled_tweets/app/models/user.rb
#email:string
#password_digest:string
#
#password:string virtual
#password_confirmation:string virtual

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ , message: "Must be a valid email address" }
end

scheduled_tweets/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

scheduled_tweets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user



  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end
end

scheduled_tweets/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

scheduled_tweets/app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end
  def create
    # render plain: params[:user]
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account Created Successfully"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

scheduled_tweets/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

scheduled_tweets/app/helpers/application_helper.rb
module ApplicationHelper
end

scheduled_tweets/app/views/about/index.html.erb
<h1>About Us</h1>

scheduled_tweets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial:"shared/navbar"%>
    <div class="container">
        <%= render partial:"shared/flash"%>
        <%= yield %>
    </div>
  </body>
</html>

scheduled_tweets/app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to Schduled Tweets</h1>
</div>

scheduled_tweets/app/views/shared/_flash.html.erb
<% if flash[:notice]%>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice]%>
    </div>
<%end%>

<% if flash[:alert]%>
    <div class="alert alert-danger mt-4" role="alert">
        <%= flash[:alert]%>
    </div>
<%end%>

scheduled_tweets/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">Menu</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link" %>
          <%# <a class="nav-link" href="about-us">About</a> %>
        </li>
      </ul>

      <ul class ="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class = "nav-item">
          <span class="navbar-text"><%= Current.user.email %></span>
        </li>
        <li class = "nav-item">
          <%= button_to "Logout", logout_path, method: :delete , class: "nav-link"%>
        </li>
        <% else %>
        <li class = "nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
        </li>
        <li class = "nav-item">
          <%= link_to "Login", sign_in_path, class: "nav-link" %>
        </li>
        <% end%>
      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>